name: Generate QR Code

on:
  repository_dispatch:
    types: [generate-qr]

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install qrcode[pil]

      - name: Generate QR code
        run: |
          python generate.py \
          '{"details":"${{ github.event.client_payload.details }}","qr_name":"${{ github.event.client_payload.qr_name }}"}'

      - name: Upload QR as artifact
        uses: actions/upload-artifact@v4
        with:
          name: qr-${{ github.event.client_payload.item_id }}
          path: ${{ github.event.client_payload.qr_name }}.png
          retention-days: 3
